name: Publish

on:
  push:
    branches:
    - main

concurrency:
  group:              ${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY:   ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    name:     Setup release
    runs-on:  ubuntu-20.04
    outputs:
      date: ${{ steps.datetime.outputs.date }}
      tag:  ${{ steps.semantic.outputs.version_tag }}
      url:  ${{ steps.marketplace.outputs.url }}
      edit: ${{ steps.action.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Datetime
        id:   datetime
        run:  echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Semantic version
        uses: paulhatch/semantic-version@v4.0.2
        id:   semantic
        with:
          short_tags: true

      - name: Marketplace release
        id:   marketplace
        run:  echo ::set-output name=url::${{ 'https://github.com/marketplace/actions/github-action-template?version=' }}$RELEASE_VERSION
        env:
          RELEASE_VERSION: ${{ steps.semantic.outputs.version_tag }}

      - name: Marketplace release creation
        id:   action
        run:  echo ::set-output name=url::${{ 'https://github.com/covalentteam/template/releases/edit/' }}$RELEASE_VERSION
        env:
          RELEASE_VERSION: ${{ steps.semantic.outputs.version_tag }}

  code-standards:
    name:     Code standards
    runs-on:  ubuntu-20.04
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  unit-test:
    name:     Unit tests
    runs-on:  ubuntu-20.04
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing
        run:  go test ./...

  publish-version:
    name: Publish version
    runs-on: ubuntu-20.04
    needs:
      - setup
      - unit-test
      - code-standards
    environment:
      name: Marketplace
      url:  ${{ needs.setup.outputs.edit }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          flavor: latest=true
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags:   ${{ needs.setup.outputs.tag }}

      - name: GHRC Authentication
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACCESS_USER }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          push:      true
          target:    final
          platforms: linux/amd64
          context:   .
          file:      .build/Dockerfile
          tags:      ${{ steps.meta.outputs.tags }}
          build-args: |
            RELEASE_REVISION=${{ github.event.after }}
            RELEASE_REFERENCE=${{ github.event.before }}
            RELEASE_CREATED_AT=${{ needs.setup.outputs.date }}
            RELEASE_VERSION=${{ needs.setup.outputs.tag }}
            RELEASE_DESCRIPTION=${{ needs.setup.outputs.tag }}
            RELEASE_URL=${{ needs.setup.outputs.url }}

  publish-release:
    name:     Publish release
    runs-on:  ubuntu-20.04
    needs:
      - setup
      - unit-test
      - code-standards
    environment:
      name: Marketplace
      url: ${{ needs.setup.outputs.edit }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish tag
        uses: mathieudutour/github-tag-action@v5.6
        id: tagging
        with:
          dry_run: true
          github_token: ${{ secrets.ACCESS_TOKEN }}
          custom_tag: ${{ needs.setup.outputs.tag }}

      - name: Publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          prerelease: true
          release_name: Release ${{ needs.tagging.outputs.tag }}
          tag_name:     ${{ needs.setup.outputs.tag }}
          body:         ${{ steps.tagging.outputs.changelog }}
